@startuml


loop true
    main --> Monitoring: monitoringCanData()
        Monitoring-->Parser: getCanData()
        Parser-->Monitoring: id, length data
        alt 対象CANID
        Monitoring ->> main: E_DataKind, data
        end

    alt 対象CANID
        main-->Sender: sendCanData()
        Sender-->main: 
    end
end

@enduml